services:
  postgres:
    image: postgres:16
    container_name: growtwitter_db
    environment:
      POSTGRES_USER: growtwitter
      POSTGRES_PASSWORD: growtwitter
      POSTGRES_DB: growtwitter
    ports:
      - "5433:5432"
    volumes:
      - growtwitter_data:/var/lib/postgresql/data

volumes:
  growtwitter_data:
